"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Circle_1 = require("./Circle");
var Cylinder_1 = require("./Cylinder");
var Rectangle_1 = require("./Rectangle");
var Square_1 = require("./Square");
var circle = new Circle_1.Circle("circle", 10);
var cylinder = new Cylinder_1.Cylinder("cylinder", 15, 10);
var rectangle = new Rectangle_1.Rectangle(10, 20, "rectangle");
var square = new Square_1.Square("square", 15);
console.log("--circle--");
console.log(circle.radius);
circle.resize(50);
console.log(circle.radius);
console.log("--cylinder--");
console.log(cylinder.radius);
console.log(cylinder.height);
cylinder.resize(50);
console.log(cylinder.radius);
console.log(cylinder.height);
console.log("--rectangle--");
console.log(rectangle.width);
console.log(rectangle.height);
rectangle.resize(50);
console.log(rectangle.width);
console.log(rectangle.height);
console.log("--square--");
console.log(square.width);
console.log(square.height);
square.resize(50);
console.log(square.width);
console.log(square.height);
